version: '3'
services:
  node.react:
    build:
      context: ./docker
      dockerfile: Dockerfile
    image: node:14.17-alpine3.10
    ports:
      - '${APP_PORT:-3000}:3000'
    volumes:
      - '.:/var/www/html'
    networks:
      - sail
    stdin_open: true
networks:
  sail:
    driver: bridge
volumes:
  nodeReact:
    driver: local
